package com.amex.lumi.beam.parser;

import com.amex.lumi.beam.model.EmployeeRecord;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.util.List;


public class JsonEmployeeParser {

    private final ObjectMapper objectMapper;


    public JsonEmployeeParser(ObjectMapper objectMapper) {
        this.objectMapper = objectMapper;
    }


    /**
     * Parses the original Lumi JSON array format.
     *
     * Example:
     *
     * [
     *   {...},
     *   {...}
     * ]
     */
    public List<EmployeeRecord> parse(
            String json) throws JsonProcessingException {

        return objectMapper.readValue(
                json,
                new TypeReference<List<EmployeeRecord>>() {
                }
        );
    }


    /**
     * Parses one employee JSON object.
     *
     * Used for JSON Lines generated by PySpark.
     *
     * Example:
     *
     * {"employee_id":"EMP001", ...}
     */
    public EmployeeRecord parseRecord(
            String json) throws JsonProcessingException {

        return objectMapper.readValue(
                json,
                EmployeeRecord.class
        );
    }
}
